# Generated by Django 2.2.6 on 2019-10-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='contents',
            field=models.TextField(max_length=40),
        ),
    ]
